### ISSUE TITLE
Ability to remove standard EFab recipes?

### ISSUE THREAD

**Issue by JareeZy** [Hubry/EFabCTBindings#1]
So, EFab comes with its standard recipes to build the more advanced components within its own crafting system. I'd like to remove those recipes and substitute my own.

Is there a EFabRecipe.remove() function or could it be added?

Thank you kindly for your time!

**Comment by Hubry** [comment]
I completely forgot about this repo, so I guess this might be a bit too late for you, but the way to do this would be telling EFab to dump its recipes and remove all recipes from its recipe config.
